### ISSUE TITLE
Properties not set?

### ISSUE THREAD

**Issue by cxvoth** [antonwierenga/amazonmq-cli#2]
The custom properties appear to be ignored. When sending a message using --file with <property> elements set, they are missing from the message.

**Comment by antonwierenga** [comment]
Can you show me a reproduce case?

Below is an example file with a custom property. If you send this to a queue the custom property is not ignored. You can verify this with list-messages command.

```
<jms-messages> 
  <jms-message>
    <properties>
      <property>
        <name>my_custom_property</name>
        <value>1</value>
      </property>        
    </properties>      
    <body><![CDATA[<?xml version="1.0"?>
<catalog>
   <book id="1">
      <author>Basil, Matthew</author>
      <title>XML Developer's Guide</title>
      <genre>Computer</genre>
      <price>44.95</price>
      <publish_date>2002-10-01</publish_date>
      <description>An in-depth look at creating applications with XML.</description>
   </book>
</catalog>]]></body>
  </jms-message>  
</jms-messages>
```

**Comment by cxvoth** [comment]
I used the exact sample message you provided.
When I browse the message or use the ActiveMQ web console there are no properties set.
I am using ActiveMQ 5.15 (installed to Kubernetes on GCP) (with no custom configuration)
https://console.cloud.google.com/marketplace/details/google/activemq

browse-messages --queue test

<jms-message>
  <header>
    <message-id>ID:antimatter-39255-1593965576084-3:1:1:1:1</message-id>
    <delivery-mode>2</delivery-mode>
    <destination>queue://test</destination>
    <expiration>0</expiration>
    <priority>3</priority>
    <redelivered>false</redelivered>
    <timestamp>2020-07-05T12:14:48</timestamp>
  </header>
  <body><![CDATA[<?xml version="1.0"?> <catalog> <book id="1"> <author>Basil, Matthew</author> <title>XML Developer's Guide</title> <genre>Computer</genre> <price>44.95</price> <publish_date>2002-10-01</publish_date> <description>An in-depth look at creating applications with XML.</description> </book> </catalog>]]></body>
</jms-message>

**Comment by antonwierenga** [comment]
My bad (I thought this was an [activemq-cli](https://github.com/antonwierenga/activemq-cli) issue). I can reproduce this issue and created a [fix release](https://github.com/antonwierenga/amazonmq-cli/releases/tag/v0.2.2). Thanks for the bug report!
